#pragma once

#include "../API.h"

namespace Euler {

	enum EULER_API Key {

		ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO, NUMPAD_ONE, NUMPAD_TWO, NUMPAD_THREE, NUMPAD_FOUR, NUMPAD_FIVE, NUMPAD_SIX, NUMPAD_SEVEN, NUMPAD_EIGHT, NUMPAD_NINE, NUMPAD_ZERO,
		Q, W, E, R, T, Y, U, I, O, P, A, S, D, F, G, H, J, K, L, Z, X, C, V, B, N, M,
		TILDE, MINUS, NUMPAD_MINUS, EQUAL, NUMPAD_PLUS, BRACKET_OPEN, BRACKET_CLOSE, SEMICOLON, APOSTROPHE, COMMA, DOT, NUMPAD_DOT, BACKSLASH, SLASH, NUMPAD_ASTERISK,
		
		MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT,
		CTRL, CTRL_RIGHT, ALT, ALT_RIGHT, SHIFT, SHIFT_RIGHT, CAPS_LOCK, TAB, ESC, SPACE, ENTER, NUMPAD_ENTER, BACKSPACE,
		ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT

	};

}
